### ISSUE TITLE
Question: how varstack differs from the yamlex salt renderer?

### ISSUE THREAD

**Issue by bbinet** [conversis/varstack#3]
salt.renderers.yamlex: http://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.yamlex.html

Is there any varstack feature which is not supported by the yamlex salt renderer?

**Comment by bbinet** [comment]
Any thought also on pepa, which seems similar?
https://github.com/mickep76/pepa

**Comment by dennisjac** [comment]
salt.renderers.yamlex only seems to work within a single file. Varstack joins data from various files which are chosen based on grains.

I've looked at pepa but I'm not even sure I understand correctly how it works. I'm not sure what the ".." in the keys is supposed to accomplish.

**Comment by bbinet** [comment]
Thanks, I'll give varstack a try.

> salt.renderers.yamlex only seems to work within a single file. Varstack
> joins data from various files which are chosen based on grains.
> 
> Ok, that is good to know.
> Also it would be great if varstack could choose files to load based on
> pillar data (in addition to grains), because pillar data is safer than
> grains.
> 
> I've looked at pepa but I'm not even sure I understand correctly how it
> works. I'm not sure what the ".." in the keys is supposed to accomplish.
> 
> I also have trouble to understand how it works, and the ".." syntax is not
> usual and quite verbose.

On the contrary, varstack doc is clear, and it seems to be a good fit with
my needs, except the fact that I need varstack to be able to interpolate
variable from existing pillar data: should I create a new github issue for
that?

**Comment by dennisjac** [comment]
Right now Salt doesn't support accessing previously defined pillar data in another pillar. See https://github.com/saltstack/salt/issues/6955 for more info.

**Comment by bbinet** [comment]
When reading the documentation for saltstack `ext_pillar` function, previous pillar data seem to be available as the second argument of the `ext_pillar` function:
http://docs.saltstack.com/en/latest/topics/development/external_pillars.html#ext-pillar

So this seem to be possible, isn't it?

**Comment by bbinet** [comment]
FYI, this actually possible for an `ext_pillar` to use previous pillar data: this what I've done in my PillarStack `ext_pillar`: https://github.com/bbinet/pillarstack
